name: Push to Docker Hub

on:
  push:
    tags:
      - 'v**'

jobs:
  push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zeroedbooks/deploy
          tags: latest,${{ steps.get_version.outputs.VERSION }}
          add_git_labels: true
